language: rust

rust:
  - stable
  - beta
  - nightly
  - 1.26.0

script:
  - export RUSTFLAGS="-D warnings"
  - cargo test -- --test-threads=1
  - |
    if [[ $TRAVIS_RUST_VERSION == nightly ]]; then
      cd benchmarks
      cargo build --bins
    fi
