language: rust

rust:
  - stable
  - beta
  - nightly
  - 1.26.0

script:
  - export RUSTFLAGS="-D warnings"
  - cargo build
  - cargo build --release
  - cargo test -- --test-threads=1
  - cargo test --release -- --test-threads=1
