language: rust

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.8

rust:
  - 1.25.0
  - 1.26.0
  - stable
  - beta
  - nightly

script:
  - ./ci/script.sh
  - (cd crossbeam-utils && ./ci/script.sh)
