language: rust

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.8
    packages:
      - llvm-3.8
      - llvm-3.8-dev
      - clang-3.8
      - clang-3.8-dev

matrix:
  include:

  - rust: 1.26.0
    name: "crossbeam on 1.26.0"
    script: ./ci/script.sh
  - rust: stable
    name: "crossbeam on stable"
    script: ./ci/script.sh

  - rust: 1.26.0
    name: "crossbeam-channel on 1.26.0"
    script: ./crossbeam-channel/ci/script.sh
  - rust: stable
    name: "crossbeam-channel on stable"
    script: ./crossbeam-channel/ci/script.sh

  # - name: "crossbeam-deque"
  #   script: ./crossbeam-deque/ci/script.sh
  #
  # - name: "crossbeam-epoch"
  #   script: ./crossbeam-epoch/ci/script.sh
  #
  # - name: "crossbeam-skiplist"
  #   script: ./crossbeam-skiplist/ci/script.sh
  #
  # - name: "crossbeam-utils"
  #   script: ./crossbeam-utils/ci/script.sh
