language: rust

rust:
  - stable
  - beta
  - nightly
  - 1.26.0

install:
  - cargo install cargo-tree

script:
  # TODO(stjepang): Uncomment the following line once we fix the dependency tree
  # - (cargo tree --duplicate | grep ^crossbeam) && exit 1
  - ./ci/script.sh
  - (cd crossbeam-utils && ./ci/script.sh)
