[package]
name = "channel"
version = "0.1.0"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
license = "Apache-2.0/MIT"

[dependencies]
coco = { path = "../coco" }
crossbeam = "*"
either = "1.1"
rand = "0.3"
