[package]
name = "crossbeam-deque"
version = "0.1.0"
authors = ["The Crossbeam Project Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/crossbeam-rs/crossbeam-deque"
homepage = "https://github.com/crossbeam-rs/crossbeam-deque"
documentation = "https://docs.rs/crossbeam-deque"
description = "Concurrent work-stealing deque"
keywords = ["Chase-Lev", "lock-free", "scheduler", "scheduling"]
categories = ["concurrency", "data-structures"]

[badges]
travis-ci = { repository = "crossbeam-rs/crossbeam-deque" }

[dependencies]
crossbeam-epoch = { git = "https://github.com/stjepang/crossbeam-epoch", branch = "guard" }
crossbeam-utils = { git = "https://github.com/crossbeam-rs/crossbeam-utils" }

[dev-dependencies]
rand = "0.3"
