[package]
name = "crossbeam"
version = "0.1.0"
authors = ["Aaron Turon <aturon@mozilla.com>"]
description = "Support for lock-free data structures, synchronizers, and parallel programming"
repository = "https://github.com/aturon/crossbeam"
documentation = "http://aturon.github.io/crossbeam-doc/crossbeam/"
