[package]
name = "crossbeam"
# When publishing a new version:
# - Update CHANGELOG.md
# - Update README.md
# - Create "crossbeam-X.Y.Z" git tag
version = "0.4.1"
authors = ["The Crossbeam Project Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/crossbeam-rs/crossbeam"
homepage = "https://github.com/crossbeam-rs/crossbeam"
documentation = "https://docs.rs/crossbeam"
description = "Support for concurrent programming: memory management, utilities, non-blocking data structures"
keywords = ["atomic", "garbage", "non-blocking", "lock-free", "rcu"]
categories = ["concurrency", "memory-management", "data-structures"]

[badges]
travis-ci = { repository = "crossbeam-rs/crossbeam" }

[features]
default = ["use_std"]
nightly = ["crossbeam-epoch/nightly", "crossbeam-utils/nightly"]
use_std = ["crossbeam-epoch/use_std", "crossbeam-utils/use_std"]

[dependencies]
crossbeam-channel = "0.2"
crossbeam-deque = "0.6"
crossbeam-epoch = "0.5"
crossbeam-utils = "0.5"

[dev-dependencies]
rand = "0.5"

[workspace]
members = [
  ".",
  "crossbeam-channel",
  "crossbeam-channel/benchmarks",
  "crossbeam-deque",
  "crossbeam-epoch",
  "crossbeam-skiplist",
  "crossbeam-utils",
]

[patch.crates-io]
# crossbeam = { path = "." }
# crossbeam-channel = { path = "./crossbeam-channel" }
# crossbeam-deque = { path = "./crossbeam-deque" }
# crossbeam-epoch = { path = "./crossbeam-epoch" }
# crossbeam-skiplist = { path = "./crossbeam-skiplist" }
# crossbeam-utils = { path = "./crossbeam-utils" }
