[package]
name = "benchmark"
version = "0.1.0"

[dependencies]
chan = "0.1.19"
channel = { path = ".." }
crossbeam = "0.3.0"

[[bin]]
name = "channel"
path = "channel.rs"

[[bin]]
name = "chan"
path = "chan.rs"

[[bin]]
name = "mpsc"
path = "mpsc.rs"

[[bin]]
name = "ms_queue"
path = "ms_queue.rs"

[[bin]]
name = "seg_queue"
path = "seg_queue.rs"
